console.log(document.title);
document.title="Javascript DOM";
console.log(document.title);
console.log(document.URL);
console.log(document.head);
console.log(document.body);
console.log(document.images);
console.log(document.links);
console.log(document.scripts);
console.log(document.styleSheets);
console.log(document.forms);